# Gestão de risco

## Começando do começo: o que é risco?

> “A palavra 'risco' deriva do italiano antigo risicare, que significa ‘ousar’. Neste sentido, o risco é uma opção, e não um destino" (Bernstein 2011, 8).

> "A ideia revolucionária que define a fronteira entre os tempos modernos e o passado é o domínio do risco: a noção de que o futuro é mais do que um capricho dos deuses e de que homens e mulheres não são passivos ante a natureza". [@bernstein_desafio_2011, p. 1]

## Ferramentas fundantes da gestão de risco

__1654__: Descoberta a teoria das probabilidades por Blaise Pascal e Pierre de Fermat, criando a primeira matriz de conhecimento capaz de habilitar a tomada de decisões com base em previsões de futuro feitas com números.

__1703__: "Gottfried von Leibniz comentou com o cientista e matemático suíço Jacob Bernoulli que 'a natureza estabeleceu padrões que dão origem ao retorno dos eventos, mas apenas na maior parte dos casos', levando assim Bernoulli a inventar a Lei dos Grandes Números e os métodos de amostragem estatística (...) A advertência de Leibniz “mas apenas na maior parte dos casos” – foi mais profunda do que ele possa ter percebido, pois forneceu a chave para a questão da existência do risco em primeiro lugar: sem esta ressalva, tudo seria previsível, e em um mundo onde cada evento é idêntico a um evento anterior nenhuma mudança jamais ocorreria" [@bernstein_desafio_2011, p. 5]

__1730__: A estrutura da distribuição normal e o conceito de desvio-padrão (Lei das Médias) são descobertos e sistematizados por Abraham de Moivre.

__1738__: Daniel Beurnolli lança a ideia de que a satisfação resultante de qualquer pequeno aumento de riqueza “será inversamente proporcional à quantidade de bens anteriormente possuídos”. E então "Bernoulli explicou por que o rei Midas era um homem infeliz, por que as pessoas tendem a ser avessas ao risco e por que os preços têm de cair para que os clientes sejam persuadidos a comprar mais" [@bernstein_desafio_2011, pp. 5:6]

__1740 - 1760__: Thomas Bayes cria o teorema de Bayes, que só se populariza após sua morte.

## Abordagens de gestão de risco

## A análise de crédito: focos e preocupações


